//SPDX-License-Identifier: Unlicense
pragma solidity ^0.8.0;

enum FsEvent {
    EVENT_FS_STORE_FILE,
	EVENT_FS_DELETE_FILE,
	EVENT_FS_DELETE_FILES,
	EVENT_FS_SET_USER_SPACE,
	EVENT_FS_REG_NODE,
    EVENT_FS_UN_REG_NODE,
	EVENT_FS_PROVE_FILE,
    EVENT_FS_FILE_PDP_SUCCESS,
	EVENT_FS_CREATE_SECTOR,
	EVENT_FS_DELETE_SECTOR
}
